spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: password
    url: jdbc:h2:file:~/messages
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rsocket:
    server:
      ssl:
        key-store: classpath:testkey.jks
        key-store-type: pkcs12
        key-store-password: password
        key-password: password
        key-alias: testkey
      port: 8443